#!/bin/bash
# This job should be submitted from within sundials-gptune/src/diffusion/multifidelity directory
#BSUB -P CSC326
#BSUB -q killable
#BSUB -W 4:00
#BSUB -nnodes 1
#BSUB -J diffusion-cvode-newton-gmres-multifidelity
#BSUB -o diffusion-cvode-newton-gmres-multifidelity.out
#BSUB -e diffusion-cvode-newton-gmres-multifidelity.err

. ../../setup-env-summit.sh
jsrun -n 1 python diffusion-cvode-multifidelity.py -nloop 8 -newton_gmres -gen_plots
