#!/bin/bash
# This job should be submitted from within sundials-gptune/src/diffusion/ directory
#BSUB -P CSC326
#BSUB -q killable
#BSUB -W 4:00
#BSUB -nnodes 1
#BSUB -J diffusion-cvode-fixedpoint-multifidelity
#BSUB -o diffusion-cvode-fixedpoint-multifidelity.out
#BSUB -e diffusion-cvode-fixedpoint-multifidelity.err

. ../setup-env-summit.sh
jsrun -n 1 python diffusion-cvode-fixedpoint-multifidelity.py -nrun 4
