#!/bin/bash
# This job should be submitted from within sundials-gptune/src/diffusion/standard directory
#BSUB -P CSC326
#BSUB -q killable
#BSUB -W 4:00
#BSUB -nnodes 1
#BSUB -J diffusion-cvode-fixedpoint
#BSUB -o diffusion-cvode-fixedpoint.out
#BSUB -e diffusion-cvode-fixedpoint.err
#BSUB -N

. ../../setup-env-summit.sh
jsrun -n 1 python diffusion-cvode-fixedpoint.py -nrun 120 -plot_runtimes -plot_params
