#!/bin/bash
# This job should be submitted from within sundials-gptune/src/diffusion/standard directory
#BSUB -P CSC326
#BSUB -W 10:00
#BSUB -q killable
#BSUB -nnodes 1
#BSUB -J diffusion-cvode-newton-gmres-additional
#BSUB -o diffusion-cvode-newton-gmres-additional.out
#BSUB -e diffusion-cvode-newton-gmres-additional.err
#BSUB -N

. ../../setup-env-summit.sh
jsrun -n 1 python diffusion-cvode.py -newton_gmres -nrun 300 -gen_plots -additional_params

