#!/bin/bash
# This job should be submitted from within sundials-gptune/src/diffusion/standard directory
#BSUB -P CSC326
#BSUB -W 4:00
#BSUB -q killable
#BSUB -nnodes 1
#BSUB -J diffusion-cvode-newton-gmres
#BSUB -o diffusion-cvode-newton-gmres.out
#BSUB -e diffusion-cvode-newton-gmres.err
#BSUB -N

. ../../setup-env-summit.sh
jsrun -n 1 python diffusion-cvode-newton-gmres.py -nrun 120 -gen_plots
cp ./*newton*.png ~/workspace/png
