#!/bin/bash
# This job should be submitted from within sundials-gptune/src/diffusion/standard directory
#BSUB -P CSC326
#BSUB -W 4:00
#BSUB -q killable
#BSUB -nnodes 1
#BSUB -J diffusion-cvode-1-128-newton-gmres
#BSUB -o diffusion-cvode-1-128-newton-gmres.out
#BSUB -e diffusion-cvode-1-128-newton-gmres.err
#BSUB -N

. ../../setup-env-summit.sh
jsrun -n 1 python diffusion-cvode.py -newton_gmres -nrun 300 -gen_plots -diffusion_coeff 1 -nxy 128

