#!/bin/bash
# This job should be submitted from within sundials-gptune/src/diffusion/multitask directory
#BSUB -P CSC326
#BSUB -W 24:00
#BSUB -q killable
#BSUB -nnodes 1
#BSUB -J diffusion-cvode-multitask-newton-gmres
#BSUB -o diffusion-cvode-multitask-newton-gmres.out
#BSUB -e diffusion-cvode-multitask-newton-gmres.err
#BSUB -N

. ../../setup-env-summit.sh
jsrun -n 1 python diffusion-cvode-multitask.py -newton_gmres -nrun 300 -gen_plots

