#!/bin/bash
# This job should be submitted from within sundials-gptune/src/diffusion-paper/standard directory
#BSUB -P CSC326
#BSUB -W 24:00
#BSUB -q killable
#BSUB -nnodes 1
#BSUB -J diffusion-cvode-10-128-all-additional
#BSUB -o diffusion-cvode-10-128-all-additional.out
#BSUB -e diffusion-cvode-10-128-all-additional.err
#BSUB -N

export SUNPROFILER_PRINT=./log/diffusion-cvode-10-128-all-additional.log
. ../../setup-env-summit.sh
jsrun -n 1 python diffusion-cvode.py -solve_type all -nrun 4000 -ninitial 4000 -gen_plots -kxy 10 -nxy 128 -additional_params -print_csv

