#!/bin/bash
# This job should be submitted from within sundials-gptune/src/pele directory
#BSUB -P CSC326
#BSUB -q killable
#BSUB -W 10:00
#BSUB -nnodes 1
#BSUB -J pele-dodecane_lu_qss-cvode-newton-gmres
#BSUB -o pele-dodecane_lu_qss-cvode-newton-gmres.out
#BSUB -e pele-dodecane_lu_qss-cvode-newton-gmres.err
#BSUB -N

. ../setup-env-summit.sh
jsrun -n 1 python pele-cvode.py -solve_type newton_gmres -nrun 300 -mechanism dodecane_lu_qss -gen_plots 
