#!/bin/bash
# This job should be submitted from within sundials-gptune/src/pele directory
#BSUB -P CSC326
#BSUB -q killable
#BSUB -W 10:00
#BSUB -nnodes 1
#BSUB -J pele-dodecane_lu-cvode-fixedpoint
#BSUB -o pele-dodecane_lu-cvode-fixedpoint.out
#BSUB -e pele-dodecane_lu-cvode-fixedpoint.err
#BSUB -N

. ../setup-env-summit.sh
jsrun -n 1 python pele-cvode.py -nrun 300 -gen_plots -mechanism dodecane_lu
