#!/bin/bash
# This job should be submitted from within sundials-gptune/src/pele directory
#BSUB -P CSC326
#BSUB -q killable
#BSUB -W 10:00
#BSUB -nnodes 1
#BSUB -J pele-cvode-multitask-newton-iter
#BSUB -o pele-cvode-multitask-newton-iter.out
#BSUB -e pele-cvode-multitask-newton-iter.err
#BSUB -N

. ../setup-env-summit.sh
jsrun -n 1 python pele-cvode-multitask.py -solve_type newton_iter -nrun 800 -gen_plots 
