#!/bin/bash
# This job should be submitted from within sundials-gptune/src/diffusion/diffusion-arkode-newton-gmres-multifidelity directory
#BSUB -P CSC326
#BSUB -W 2:00
#BSUB -nnodes 1
#BSUB -J diffusion-arkode-newton-gmres-multifidelity
#BSUB -o diffusion-arkode-newton-gmres-multifidelity.out
#BSUB -e diffusion-arkode-newton-gmres-multifidelity.err

. ../../setup-env-summit.sh
jsrun -n 1 python diffusion-arkode-newton-gmres-multifidelity.py -nrun 10
